apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: memcached:latest
          args:
            - "--memory-limit=1024"
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              memory: "1024Mi"
