apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.appName }}-letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.appName }}.apps.k8s.longitood.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: {{ .Values.port }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.appName }}.apps.k8s.longitood.com
      secretName: tls-{{ .Values.appName }}
