apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  type: ClusterIP
