apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-{{ .Values.name }}
  duration: 2160h0m0s
  renewBefore: 12h0m0s
  commonName: {{ .Values.name }}.apps.k8s.longitood.com
  dnsNames:
    - {{ .Values.name }}.apps.k8s.longitood.com
    - bookcover.longitood.com
  issuerRef:
    name: {{ .Values.name }}-letsencrypt
    kind: ClusterIssuer
