apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.memcached.name }}
spec:
  selector:
    app: {{ .Values.memcached.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.memcached.containerPort }}
      targetPort: {{ .Values.memcached.containerPort }}
  type: ClusterIP
