apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.appName }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-{{ .Values.appName }}
  duration: 2160h
  renewBefore: 12h
  commonName: {{ .Values.appName }}.apps.k8s.longitood.com
  dnsNames:
    - {{ .Values.appName }}.apps.k8s.longitood.com
  issuerRef:
    name: {{ .Values.appName }}-letsencrypt
    kind: ClusterIssuer
