apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.appName }}-letsencrypt
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.appName }}-letsencrypt
    solvers:
    - http01:
        ingress:
          class: traefik 

